# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/foobar.proto for package 'Proto'

require 'grpc'
require 'proto/foobar_pb'

module Proto
  module FoobarService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'foobar.FoobarService'

      rpc :TriggerRescan, ::Proto::RescanRequest, ::Proto::RescanResponse
    end

    Stub = Service.rpc_stub_class
  end
end
